
# ============================================================
# COMPLETE INDIA DISTRICT-LEVEL SOIL MAP
# All 766 districts across 36 States/UTs
# Soil Types: alluvial | black | red_laterite | mountain | arid | coastal_sandy
# ============================================================

DISTRICT_SOIL_MAP = {

    # ══════════════════════════════════════════════════════
    # ANDAMAN & NICOBAR ISLANDS (3 districts)
    # ══════════════════════════════════════════════════════
    'nicobar': 'red_laterite',
    'north and middle andaman': 'red_laterite',
    'south andaman': 'red_laterite',
    'port blair': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # ANDHRA PRADESH (26 districts)
    # ══════════════════════════════════════════════════════
    'alluri sitharama raju': 'red_laterite',
    'anakapalli': 'alluvial',
    'anantapur': 'red_laterite',
    'annamayya': 'red_laterite',
    'bapatla': 'alluvial',
    'chittoor': 'red_laterite',
    'east godavari': 'alluvial',
    'eluru': 'alluvial',
    'guntur': 'alluvial',
    'kakinada': 'alluvial',
    'konaseema': 'alluvial',
    'krishna': 'alluvial',
    'kurnool': 'black',
    'manyam': 'red_laterite',
    'nandyal': 'red_laterite',
    'ntr': 'alluvial',
    'palnadu': 'black',
    'prakasam': 'black',
    'spsr nellore': 'alluvial',
    'srikakulam': 'red_laterite',
    'sri sathya sai': 'red_laterite',
    'tirupati': 'red_laterite',
    'visakhapatnam': 'red_laterite',
    'vizianagaram': 'red_laterite',
    'west godavari': 'alluvial',
    'ys jagan mohan reddy': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # ARUNACHAL PRADESH (25 districts)
    # ══════════════════════════════════════════════════════
    'anjaw': 'mountain',
    'changlang': 'mountain',
    'dibang valley': 'mountain',
    'east kameng': 'mountain',
    'east siang': 'mountain',
    'itanagar': 'mountain',
    'kamle': 'mountain',
    'kra daadi': 'mountain',
    'kurung kumey': 'mountain',
    'lepa rada': 'mountain',
    'lohit': 'mountain',
    'longding': 'mountain',
    'lower dibang valley': 'mountain',
    'lower siang': 'mountain',
    'lower subansiri': 'mountain',
    'namsai': 'alluvial',
    'pakke kessang': 'mountain',
    'papum pare': 'mountain',
    'shi yomi': 'mountain',
    'siang': 'mountain',
    'tawang': 'mountain',
    'tirap': 'mountain',
    'upper dibang valley': 'mountain',
    'upper siang': 'mountain',
    'upper subansiri': 'mountain',
    'west kameng': 'mountain',
    'west siang': 'mountain',

    # ══════════════════════════════════════════════════════
    # ASSAM (35 districts)
    # ══════════════════════════════════════════════════════
    'bajali': 'alluvial',
    'baksa': 'alluvial',
    'barpeta': 'alluvial',
    'biswanath': 'alluvial',
    'bongaigaon': 'alluvial',
    'cachar': 'alluvial',
    'charaideo': 'red_laterite',
    'chirang': 'alluvial',
    'darrang': 'alluvial',
    'dhemaji': 'alluvial',
    'dhubri': 'alluvial',
    'dibrugarh': 'alluvial',
    'dima hasao': 'mountain',
    'goalpara': 'alluvial',
    'golaghat': 'alluvial',
    'hailakandi': 'alluvial',
    'hojai': 'alluvial',
    'jorhat': 'alluvial',
    'kamrup': 'alluvial',
    'kamrup metropolitan': 'alluvial',
    'guwahati': 'alluvial',
    'karbi anglong': 'red_laterite',
    'karimganj': 'alluvial',
    'kokrajhar': 'alluvial',
    'lakhimpur': 'alluvial',
    'majuli': 'alluvial',
    'morigaon': 'alluvial',
    'nagaon': 'alluvial',
    'nalbari': 'alluvial',
    'sivasagar': 'alluvial',
    'sonitpur': 'alluvial',
    'south salmara mankachar': 'alluvial',
    'tamulpur': 'alluvial',
    'tinsukia': 'alluvial',
    'udalguri': 'alluvial',
    'west karbi anglong': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # BIHAR (38 districts)
    # ══════════════════════════════════════════════════════
    'araria': 'alluvial',
    'arwal': 'alluvial',
    'aurangabad': 'alluvial',
    'banka': 'red_laterite',
    'begusarai': 'alluvial',
    'bhagalpur': 'alluvial',
    'bhojpur': 'alluvial',
    'buxar': 'alluvial',
    'darbhanga': 'alluvial',
    'east champaran': 'alluvial',
    'gaya': 'alluvial',
    'gopalganj': 'alluvial',
    'jamui': 'red_laterite',
    'jehanabad': 'alluvial',
    'kaimur': 'alluvial',
    'katihar': 'alluvial',
    'khagaria': 'alluvial',
    'kishanganj': 'alluvial',
    'lakhisarai': 'alluvial',
    'madhepura': 'alluvial',
    'madhubani': 'alluvial',
    'munger': 'alluvial',
    'muzaffarpur': 'alluvial',
    'nalanda': 'alluvial',
    'nawada': 'red_laterite',
    'patna': 'alluvial',
    'purnia': 'alluvial',
    'rohtas': 'alluvial',
    'saharsa': 'alluvial',
    'samastipur': 'alluvial',
    'saran': 'alluvial',
    'sheikhpura': 'alluvial',
    'sheohar': 'alluvial',
    'sitamarhi': 'alluvial',
    'siwan': 'alluvial',
    'supaul': 'alluvial',
    'vaishali': 'alluvial',
    'west champaran': 'alluvial',

    # ══════════════════════════════════════════════════════
    # CHANDIGARH (1 district - UT)
    # ══════════════════════════════════════════════════════
    'chandigarh': 'alluvial',

    # ══════════════════════════════════════════════════════
    # CHHATTISGARH (33 districts)
    # ══════════════════════════════════════════════════════
    'balod': 'red_laterite',
    'baloda bazar': 'alluvial',
    'balrampur': 'red_laterite',
    'bastar': 'red_laterite',
    'bemetara': 'alluvial',
    'bijapur cg': 'red_laterite',
    'bilaspur': 'red_laterite',
    'dantewada': 'red_laterite',
    'dhamtari': 'red_laterite',
    'durg': 'alluvial',
    'gariaband': 'red_laterite',
    'gaurela pendra marwahi': 'red_laterite',
    'janjgir champa': 'alluvial',
    'jashpur': 'red_laterite',
    'kabirdham': 'alluvial',
    'kanker': 'red_laterite',
    'khairagarh': 'red_laterite',
    'kondagaon': 'red_laterite',
    'korba': 'red_laterite',
    'koriya': 'red_laterite',
    'mahasamund': 'red_laterite',
    'manendragarh': 'red_laterite',
    'mohla manpur': 'red_laterite',
    'mungeli': 'alluvial',
    'narayanpur': 'red_laterite',
    'raigarh': 'red_laterite',
    'raipur': 'alluvial',
    'rajnandgaon': 'red_laterite',
    'sarangarh bilaigarh': 'red_laterite',
    'shakti': 'red_laterite',
    'sukma': 'red_laterite',
    'surajpur': 'red_laterite',
    'surguja': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # DADRA & NAGAR HAVELI AND DAMAN & DIU (3 districts)
    # ══════════════════════════════════════════════════════
    'dadra and nagar haveli': 'red_laterite',
    'daman': 'coastal_sandy',
    'diu': 'coastal_sandy',

    # ══════════════════════════════════════════════════════
    # DELHI (11 districts)
    # ══════════════════════════════════════════════════════
    'central delhi': 'alluvial',
    'east delhi': 'alluvial',
    'new delhi': 'alluvial',
    'north delhi': 'alluvial',
    'north east delhi': 'alluvial',
    'north west delhi': 'alluvial',
    'shahdara': 'alluvial',
    'south delhi': 'alluvial',
    'south east delhi': 'alluvial',
    'south west delhi': 'alluvial',
    'west delhi': 'alluvial',

    # ══════════════════════════════════════════════════════
    # GOA (2 districts)
    # ══════════════════════════════════════════════════════
    'north goa': 'red_laterite',
    'south goa': 'red_laterite',
    'panaji': 'red_laterite',
    'margao': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # GUJARAT (33 districts)
    # ══════════════════════════════════════════════════════
    'ahmedabad': 'black',
    'amreli': 'black',
    'anand': 'alluvial',
    'aravalli': 'alluvial',
    'banaskantha': 'arid',
    'bharuch': 'alluvial',
    'bhavnagar': 'black',
    'botad': 'black',
    'chhota udaipur': 'red_laterite',
    'dahod': 'red_laterite',
    'dang': 'red_laterite',
    'devbhoomi dwarka': 'coastal_sandy',
    'gandhinagar': 'alluvial',
    'gir somnath': 'black',
    'jamnagar': 'coastal_sandy',
    'junagadh': 'black',
    'kheda': 'alluvial',
    'kutch': 'arid',
    'mahisagar': 'alluvial',
    'mehsana': 'alluvial',
    'morbi': 'black',
    'narmada': 'alluvial',
    'navsari': 'alluvial',
    'panchmahal': 'red_laterite',
    'patan': 'arid',
    'porbandar': 'coastal_sandy',
    'rajkot': 'black',
    'sabarkantha': 'red_laterite',
    'surat': 'alluvial',
    'surendranagar': 'black',
    'tapi': 'alluvial',
    'vadodara': 'black',
    'valsad': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # HARYANA (22 districts)
    # ══════════════════════════════════════════════════════
    'ambala': 'alluvial',
    'bhiwani': 'alluvial',
    'charkhi dadri': 'alluvial',
    'faridabad': 'alluvial',
    'fatehabad': 'alluvial',
    'gurugram': 'alluvial',
    'gurgaon': 'alluvial',
    'hisar': 'alluvial',
    'jhajjar': 'alluvial',
    'jind': 'alluvial',
    'kaithal': 'alluvial',
    'karnal': 'alluvial',
    'kurukshetra': 'alluvial',
    'mahendragarh': 'alluvial',
    'nuh': 'alluvial',
    'palwal': 'alluvial',
    'panchkula': 'alluvial',
    'panipat': 'alluvial',
    'rewari': 'alluvial',
    'rohtak': 'alluvial',
    'sirsa': 'arid',
    'sonipat': 'alluvial',
    'yamunanagar': 'alluvial',

    # ══════════════════════════════════════════════════════
    # HIMACHAL PRADESH (12 districts)
    # ══════════════════════════════════════════════════════
    'bilaspur hp': 'mountain',
    'chamba': 'mountain',
    'hamirpur hp': 'mountain',
    'kangra': 'mountain',
    'kinnaur': 'mountain',
    'kullu': 'mountain',
    'lahaul and spiti': 'mountain',
    'mandi': 'mountain',
    'shimla': 'mountain',
    'sirmaur': 'mountain',
    'solan': 'mountain',
    'una': 'alluvial',

    # ══════════════════════════════════════════════════════
    # JAMMU & KASHMIR (20 districts)
    # ══════════════════════════════════════════════════════
    'anantnag': 'mountain',
    'bandipora': 'mountain',
    'baramulla': 'alluvial',
    'budgam': 'alluvial',
    'doda': 'mountain',
    'ganderbal': 'alluvial',
    'jammu': 'alluvial',
    'kathua': 'alluvial',
    'kishtwar': 'mountain',
    'kulgam': 'mountain',
    'kupwara': 'mountain',
    'poonch': 'mountain',
    'pulwama': 'alluvial',
    'rajouri': 'mountain',
    'ramban': 'mountain',
    'reasi': 'mountain',
    'samba': 'alluvial',
    'shopian': 'mountain',
    'srinagar': 'alluvial',
    'udhampur': 'mountain',

    # ══════════════════════════════════════════════════════
    # JHARKHAND (24 districts)
    # ══════════════════════════════════════════════════════
    'bokaro': 'red_laterite',
    'chatra': 'red_laterite',
    'deoghar': 'red_laterite',
    'dhanbad': 'red_laterite',
    'dumka': 'red_laterite',
    'east singhbhum': 'red_laterite',
    'garhwa': 'red_laterite',
    'giridih': 'red_laterite',
    'godda': 'red_laterite',
    'gumla': 'red_laterite',
    'hazaribagh': 'red_laterite',
    'jamtara': 'red_laterite',
    'khunti': 'red_laterite',
    'koderma': 'red_laterite',
    'latehar': 'red_laterite',
    'lohardaga': 'red_laterite',
    'pakur': 'alluvial',
    'palamu': 'red_laterite',
    'ramgarh': 'red_laterite',
    'ranchi': 'red_laterite',
    'sahebganj': 'alluvial',
    'seraikela kharsawan': 'red_laterite',
    'simdega': 'red_laterite',
    'west singhbhum': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # KARNATAKA (31 districts)
    # ══════════════════════════════════════════════════════
    'bagalkot': 'black',
    'ballari': 'red_laterite',
    'belagavi': 'black',
    'belgaum': 'black',
    'bengaluru rural': 'red_laterite',
    'bengaluru urban': 'red_laterite',
    'bangalore': 'red_laterite',
    'bengaluru': 'red_laterite',
    'bidar': 'black',
    'chamarajanagar': 'red_laterite',
    'chikkaballapur': 'red_laterite',
    'chikkamagaluru': 'alluvial',
    'chikmagalur': 'alluvial',
    'chitradurga': 'red_laterite',
    'dakshina kannada': 'red_laterite',
    'mangaluru': 'red_laterite',
    'mangalore': 'red_laterite',
    'davanagere': 'red_laterite',
    'dharwad': 'black',
    'gadag': 'black',
    'hassan': 'red_laterite',
    'haveri': 'black',
    'hubballi': 'black',
    'hubli': 'black',
    'kalaburagi': 'black',
    'gulbarga': 'black',
    'kodagu': 'red_laterite',
    'coorg': 'red_laterite',
    'kolar': 'red_laterite',
    'koppal': 'red_laterite',
    'mandya': 'red_laterite',
    'mysuru': 'red_laterite',
    'mysore': 'red_laterite',
    'raichur': 'black',
    'ramanagara': 'alluvial',
    'shivamogga': 'alluvial',
    'shimoga': 'alluvial',
    'tumakuru': 'red_laterite',
    'tumkur': 'red_laterite',
    'udupi': 'red_laterite',
    'uttara kannada': 'red_laterite',
    'karwar': 'red_laterite',
    'vijayapura karnataka': 'black',
    'vijayanagara': 'red_laterite',
    'yadgir': 'black',

    # ══════════════════════════════════════════════════════
    # KERALA (14 districts)
    # ══════════════════════════════════════════════════════
    'alappuzha': 'alluvial',
    'ernakulam': 'red_laterite',
    'idukki': 'mountain',
    'kannur': 'red_laterite',
    'kasaragod': 'red_laterite',
    'kollam': 'red_laterite',
    'kottayam': 'red_laterite',
    'kozhikode': 'red_laterite',
    'malappuram': 'red_laterite',
    'palakkad': 'red_laterite',
    'pathanamthitta': 'red_laterite',
    'thiruvananthapuram': 'red_laterite',
    'thrissur': 'red_laterite',
    'wayanad': 'mountain',

    # ══════════════════════════════════════════════════════
    # LADAKH (2 districts)
    # ══════════════════════════════════════════════════════
    'kargil': 'mountain',
    'leh': 'mountain',

    # ══════════════════════════════════════════════════════
    # LAKSHADWEEP (1 district)
    # ══════════════════════════════════════════════════════
    'lakshadweep': 'coastal_sandy',
    'kavaratti': 'coastal_sandy',

    # ══════════════════════════════════════════════════════
    # MADHYA PRADESH (55 districts)
    # ══════════════════════════════════════════════════════
    'agar malwa': 'black',
    'alirajpur': 'red_laterite',
    'anuppur': 'red_laterite',
    'ashoknagar': 'alluvial',
    'balaghat': 'red_laterite',
    'barwani': 'black',
    'betul': 'red_laterite',
    'bhind': 'alluvial',
    'bhopal': 'black',
    'burhanpur': 'black',
    'chhatarpur': 'alluvial',
    'chhindwara': 'red_laterite',
    'damoh': 'alluvial',
    'datia': 'alluvial',
    'dewas': 'black',
    'dhar': 'black',
    'dindori': 'red_laterite',
    'guna': 'black',
    'gwalior': 'alluvial',
    'harda': 'black',
    'hoshangabad': 'alluvial',
    'indore': 'black',
    'jabalpur': 'red_laterite',
    'jhabua': 'red_laterite',
    'katni': 'red_laterite',
    'khandwa': 'black',
    'khargone': 'black',
    'maihar': 'alluvial',
    'mandla': 'red_laterite',
    'mandsaur': 'black',
    'morena': 'alluvial',
    'mauganj': 'alluvial',
    'narsimhapur': 'alluvial',
    'narsinghpur': 'alluvial',
    'neemuch': 'black',
    'niwari': 'alluvial',
    'panna': 'alluvial',
    'raisen': 'alluvial',
    'rajgarh': 'black',
    'ratlam': 'black',
    'rewa': 'alluvial',
    'sagar': 'black',
    'satna': 'alluvial',
    'sehore': 'black',
    'seoni': 'red_laterite',
    'shahdol': 'red_laterite',
    'shajapur': 'black',
    'sheopur': 'alluvial',
    'shivpuri': 'alluvial',
    'sidhi': 'alluvial',
    'singrauli': 'red_laterite',
    'tikamgarh': 'alluvial',
    'ujjain': 'black',
    'umaria': 'red_laterite',
    'vidisha': 'black',

    # ══════════════════════════════════════════════════════
    # MAHARASHTRA (36 districts)
    # ══════════════════════════════════════════════════════
    'ahmednagar': 'black',
    'akola': 'black',
    'amravati': 'black',
    'aurangabad mh': 'black',
    'beed': 'black',
    'bhandara': 'red_laterite',
    'buldhana': 'black',
    'chandrapur': 'red_laterite',
    'dhule': 'black',
    'gadchiroli': 'red_laterite',
    'gondia': 'red_laterite',
    'hingoli': 'black',
    'jalgaon': 'black',
    'jalna': 'black',
    'kolhapur': 'red_laterite',
    'latur': 'black',
    'mumbai city': 'coastal_sandy',
    'mumbai suburban': 'coastal_sandy',
    'nagpur': 'black',
    'nanded': 'black',
    'nandurbar': 'red_laterite',
    'nashik': 'black',
    'osmanabad': 'black',
    'palghar': 'red_laterite',
    'parbhani': 'black',
    'pune': 'black',
    'raigad': 'red_laterite',
    'ratnagiri': 'red_laterite',
    'sangli': 'black',
    'satara': 'red_laterite',
    'sindhudurg': 'red_laterite',
    'solapur': 'black',
    'thane': 'red_laterite',
    'wardha': 'black',
    'washim': 'black',
    'yavatmal': 'black',

    # ══════════════════════════════════════════════════════
    # MANIPUR (16 districts)
    # ══════════════════════════════════════════════════════
    'bishnupur': 'alluvial',
    'chandel': 'mountain',
    'churachandpur': 'mountain',
    'imphal east': 'alluvial',
    'imphal west': 'alluvial',
    'jiribam': 'alluvial',
    'kakching': 'alluvial',
    'kamjong': 'mountain',
    'kangpokpi': 'mountain',
    'noney': 'mountain',
    'pherzawl': 'mountain',
    'senapati': 'mountain',
    'tamenglong': 'mountain',
    'tengnoupal': 'mountain',
    'thoubal': 'alluvial',
    'ukhrul': 'mountain',

    # ══════════════════════════════════════════════════════
    # MEGHALAYA (12 districts)
    # ══════════════════════════════════════════════════════
    'east garo hills': 'mountain',
    'east jaintia hills': 'mountain',
    'east khasi hills': 'mountain',
    'shillong': 'mountain',
    'eastern west khasi hills': 'mountain',
    'north garo hills': 'mountain',
    'ri bhoi': 'mountain',
    'south garo hills': 'mountain',
    'south west garo hills': 'mountain',
    'south west khasi hills': 'mountain',
    'west garo hills': 'mountain',
    'west jaintia hills': 'mountain',
    'west khasi hills': 'mountain',

    # ══════════════════════════════════════════════════════
    # MIZORAM (11 districts)
    # ══════════════════════════════════════════════════════
    'aizawl': 'mountain',
    'champhai': 'mountain',
    'hnahthial': 'mountain',
    'khawzawl': 'mountain',
    'kolasib': 'mountain',
    'lawngtlai': 'mountain',
    'lunglei': 'mountain',
    'mamit': 'mountain',
    'saiha': 'mountain',
    'saitual': 'mountain',
    'serchhip': 'mountain',

    # ══════════════════════════════════════════════════════
    # NAGALAND (16 districts)
    # ══════════════════════════════════════════════════════
    'chumoukedima': 'mountain',
    'dimapur': 'alluvial',
    'kiphire': 'mountain',
    'kohima': 'mountain',
    'longleng': 'mountain',
    'mokokchung': 'mountain',
    'mon': 'mountain',
    'niuland': 'mountain',
    'noklak': 'mountain',
    'peren': 'mountain',
    'phek': 'mountain',
    'shamator': 'mountain',
    'tseminyu': 'mountain',
    'tuensang': 'mountain',
    'wokha': 'mountain',
    'zunheboto': 'mountain',

    # ══════════════════════════════════════════════════════
    # ODISHA (30 districts)
    # ══════════════════════════════════════════════════════
    'angul': 'red_laterite',
    'balangir': 'red_laterite',
    'balasore': 'alluvial',
    'baragarh': 'alluvial',
    'bhadrak': 'alluvial',
    'boudh': 'red_laterite',
    'cuttack': 'alluvial',
    'deogarh': 'red_laterite',
    'dhenkanal': 'red_laterite',
    'gajapati': 'red_laterite',
    'ganjam': 'red_laterite',
    'jagatsinghpur': 'alluvial',
    'jajpur': 'alluvial',
    'jharsuguda': 'red_laterite',
    'kalahandi': 'red_laterite',
    'kandhamal': 'red_laterite',
    'kendrapara': 'alluvial',
    'kendujhar': 'red_laterite',
    'khordha': 'alluvial',
    'bhubaneswar': 'alluvial',
    'koraput': 'red_laterite',
    'malkangiri': 'red_laterite',
    'mayurbhanj': 'red_laterite',
    'nabarangpur': 'red_laterite',
    'nayagarh': 'red_laterite',
    'nuapada': 'red_laterite',
    'puri': 'coastal_sandy',
    'rayagada': 'red_laterite',
    'sambalpur': 'red_laterite',
    'sonepur': 'red_laterite',
    'sundargarh': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # PUDUCHERRY (4 districts)
    # ══════════════════════════════════════════════════════
    'karaikal': 'alluvial',
    'mahe': 'red_laterite',
    'puducherry': 'alluvial',
    'pondicherry': 'alluvial',
    'yanam': 'alluvial',

    # ══════════════════════════════════════════════════════
    # PUNJAB (23 districts)
    # ══════════════════════════════════════════════════════
    'amritsar': 'alluvial',
    'barnala': 'alluvial',
    'bathinda': 'alluvial',
    'faridkot': 'alluvial',
    'fatehgarh sahib': 'alluvial',
    'fazilka': 'arid',
    'ferozepur': 'alluvial',
    'gurdaspur': 'alluvial',
    'hoshiarpur': 'alluvial',
    'jalandhar': 'alluvial',
    'kapurthala': 'alluvial',
    'ludhiana': 'alluvial',
    'malerkotla': 'alluvial',
    'mansa': 'alluvial',
    'moga': 'alluvial',
    'mohali': 'alluvial',
    'muktsar': 'arid',
    'nawanshahr': 'alluvial',
    'pathankot': 'alluvial',
    'patiala': 'alluvial',
    'rupnagar': 'alluvial',
    'ropar': 'alluvial',
    'sangrur': 'alluvial',
    'shaheed bhagat singh nagar': 'alluvial',
    'tarn taran': 'alluvial',

    # ══════════════════════════════════════════════════════
    # RAJASTHAN (50 districts)
    # ══════════════════════════════════════════════════════
    'ajmer': 'arid',
    'alwar': 'alluvial',
    'anupgarh': 'arid',
    'balotra': 'arid',
    'banswara': 'red_laterite',
    'baran': 'alluvial',
    'barmer': 'arid',
    'beawar': 'arid',
    'bharatpur': 'alluvial',
    'bhilwara': 'red_laterite',
    'bikaner': 'arid',
    'bundi': 'alluvial',
    'chittorgarh': 'red_laterite',
    'churu': 'arid',
    'dausa': 'alluvial',
    'deeg': 'alluvial',
    'dhaulpur': 'alluvial',
    'didwana kuchaman': 'arid',
    'dungarpur': 'red_laterite',
    'ganganagar': 'alluvial',
    'gangapur city': 'alluvial',
    'hanumangarh': 'alluvial',
    'jaipur': 'alluvial',
    'jaipur rural': 'alluvial',
    'jaisalmer': 'arid',
    'jalore': 'arid',
    'jhalawar': 'black',
    'jhunjhunu': 'arid',
    'jodhpur': 'arid',
    'jodhpur rural': 'arid',
    'karauli': 'alluvial',
    'kekri': 'arid',
    'kota': 'black',
    'kotputli': 'alluvial',
    'nagaur': 'arid',
    'neem ka thana': 'alluvial',
    'pali': 'arid',
    'pratapgarh': 'red_laterite',
    'rajsamand': 'red_laterite',
    'salumbar': 'red_laterite',
    'sanchore': 'arid',
    'sawai madhopur': 'alluvial',
    'shahpura': 'alluvial',
    'sikar': 'arid',
    'sirohi': 'arid',
    'sri ganganagar': 'alluvial',
    'tonk': 'alluvial',
    'udaipur': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # SIKKIM (6 districts)
    # ══════════════════════════════════════════════════════
    'east sikkim': 'mountain',
    'gangtok': 'mountain',
    'north sikkim': 'mountain',
    'pakyong': 'mountain',
    'soreng': 'mountain',
    'south sikkim': 'mountain',
    'west sikkim': 'mountain',

    # ══════════════════════════════════════════════════════
    # TAMIL NADU (38 districts)
    # ══════════════════════════════════════════════════════
    'ariyalur': 'alluvial',
    'chengalpattu': 'red_laterite',
    'chennai': 'alluvial',
    'coimbatore': 'red_laterite',
    'cuddalore': 'alluvial',
    'dharmapuri': 'red_laterite',
    'dindigul': 'red_laterite',
    'erode': 'red_laterite',
    'kallakurichi': 'alluvial',
    'kanchipuram': 'alluvial',
    'kanyakumari': 'red_laterite',
    'karur': 'red_laterite',
    'krishnagiri': 'red_laterite',
    'madurai': 'red_laterite',
    'mayiladuthurai': 'alluvial',
    'nagapattinam': 'alluvial',
    'namakkal': 'red_laterite',
    'nilgiris': 'mountain',
    'ooty': 'mountain',
    'perambalur': 'alluvial',
    'pudukkottai': 'black',
    'ramanathapuram': 'coastal_sandy',
    'ranipet': 'alluvial',
    'salem': 'red_laterite',
    'sivaganga': 'red_laterite',
    'tenkasi': 'red_laterite',
    'thanjavur': 'alluvial',
    'the nilgiris': 'mountain',
    'theni': 'red_laterite',
    'thoothukudi': 'coastal_sandy',
    'tiruchirappalli': 'alluvial',
    'tirunelveli': 'red_laterite',
    'tirupathur': 'red_laterite',
    'tiruppur': 'red_laterite',
    'tiruvallur': 'alluvial',
    'tiruvannamalai': 'red_laterite',
    'tiruvarur': 'alluvial',
    'vellore': 'alluvial',
    'viluppuram': 'alluvial',
    'virudhunagar': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # TELANGANA (33 districts)
    # ══════════════════════════════════════════════════════
    'adilabad': 'red_laterite',
    'bhadradri kothagudem': 'red_laterite',
    'hanamkonda': 'black',
    'hyderabad': 'black',
    'jagtial': 'black',
    'jangaon': 'black',
    'jayashankar bhupalpally': 'red_laterite',
    'jogulamba gadwal': 'black',
    'kamareddy': 'black',
    'karimnagar': 'black',
    'khammam': 'red_laterite',
    'kumuram bheem': 'red_laterite',
    'mahabubabad': 'red_laterite',
    'mahabubnagar': 'black',
    'mancherial': 'black',
    'medak': 'black',
    'medchal malkajgiri': 'red_laterite',
    'mulugu': 'red_laterite',
    'nagarkurnool': 'black',
    'nalgonda': 'black',
    'narayanpet': 'black',
    'nirmal': 'black',
    'nizamabad': 'black',
    'peddapalli': 'black',
    'rajanna sircilla': 'black',
    'ranga reddy': 'red_laterite',
    'sangareddy': 'black',
    'siddipet': 'black',
    'suryapet': 'black',
    'vikarabad': 'red_laterite',
    'wanaparthy': 'black',
    'warangal': 'black',
    'yadadri bhuvanagiri': 'red_laterite',

    # ══════════════════════════════════════════════════════
    # TRIPURA (8 districts)
    # ══════════════════════════════════════════════════════
    'dhalai': 'mountain',
    'gomati': 'alluvial',
    'khowai': 'alluvial',
    'north tripura': 'mountain',
    'sepahijala': 'alluvial',
    'agartala': 'alluvial',
    'south tripura': 'alluvial',
    'unakoti': 'mountain',
    'west tripura': 'alluvial',

    # ══════════════════════════════════════════════════════
    # UTTAR PRADESH (75 districts)
    # ══════════════════════════════════════════════════════
    'agra': 'alluvial',
    'aligarh': 'alluvial',
    'ambedkar nagar': 'alluvial',
    'amethi': 'alluvial',
    'amroha': 'alluvial',
    'auraiya': 'alluvial',
    'ayodhya': 'alluvial',
    'azamgarh': 'alluvial',
    'baghpat': 'alluvial',
    'bahraich': 'alluvial',
    'ballia': 'alluvial',
    'balrampur': 'alluvial',
    'banda': 'alluvial',
    'barabanki': 'alluvial',
    'bareilly': 'alluvial',
    'basti': 'alluvial',
    'bhadohi': 'alluvial',
    'bijnor': 'alluvial',
    'budaun': 'alluvial',
    'bulandshahr': 'alluvial',
    'chandauli': 'alluvial',
    'chitrakoot': 'alluvial',
    'deoria': 'alluvial',
    'etah': 'alluvial',
    'etawah': 'alluvial',
    'farrukhabad': 'alluvial',
    'fatehpur': 'alluvial',
    'firozabad': 'alluvial',
    'gautam buddha nagar': 'alluvial',
    'noida': 'alluvial',
    'ghaziabad': 'alluvial',
    'ghazipur': 'alluvial',
    'gonda': 'alluvial',
    'gorakhpur': 'alluvial',
    'hamirpur up': 'alluvial',
    'hapur': 'alluvial',
    'hardoi': 'alluvial',
    'hathras': 'alluvial',
    'jalaun': 'alluvial',
    'jaunpur': 'alluvial',
    'jhansi': 'alluvial',
    'kannauj': 'alluvial',
    'kanpur dehat': 'alluvial',
    'kanpur nagar': 'alluvial',
    'kasganj': 'alluvial',
    'kaushambi': 'alluvial',
    'kushinagar': 'alluvial',
    'lakhimpur kheri': 'alluvial',
    'lalitpur': 'alluvial',
    'lucknow': 'alluvial',
    'maharajganj': 'alluvial',
    'mahoba': 'alluvial',
    'mainpuri': 'alluvial',
    'mathura': 'alluvial',
    'mau': 'alluvial',
    'meerut': 'alluvial',
    'mirzapur': 'alluvial',
    'moradabad': 'alluvial',
    'muzaffarnagar': 'alluvial',
    'pilibhit': 'alluvial',
    'pratapgarh up': 'alluvial',
    'prayagraj': 'alluvial',
    'allahabad': 'alluvial',
    'rae bareli': 'alluvial',
    'rampur': 'alluvial',
    'saharanpur': 'alluvial',
    'sambhal': 'alluvial',
    'sant kabir nagar': 'alluvial',
    'sant ravidas nagar': 'alluvial',
    'shahjahanpur': 'alluvial',
    'shamli': 'alluvial',
    'shravasti': 'alluvial',
    'siddharthnagar': 'alluvial',
    'sitapur': 'alluvial',
    'sonbhadra': 'red_laterite',
    'sultanpur': 'alluvial',
    'unnao': 'alluvial',
    'varanasi': 'alluvial',

    # ══════════════════════════════════════════════════════
    # UTTARAKHAND (13 districts)
    # ══════════════════════════════════════════════════════
    'almora': 'mountain',
    'bageshwar': 'mountain',
    'chamoli': 'mountain',
    'champawat': 'mountain',
    'dehradun': 'alluvial',
    'haridwar': 'alluvial',
    'nainital': 'mountain',
    'pauri garhwal': 'mountain',
    'pithoragarh': 'mountain',
    'rudraprayag': 'mountain',
    'tehri garhwal': 'mountain',
    'udham singh nagar': 'alluvial',
    'uttarkashi': 'mountain',

    # ══════════════════════════════════════════════════════
    # WEST BENGAL (23 districts)
    # ══════════════════════════════════════════════════════
    'alipurduar': 'alluvial',
    'bankura': 'red_laterite',
    'birbhum': 'alluvial',
    'cooch behar': 'alluvial',
    'dakshin dinajpur': 'alluvial',
    'darjeeling': 'mountain',
    'hooghly': 'alluvial',
    'howrah': 'alluvial',
    'jalpaiguri': 'alluvial',
    'jhargram': 'red_laterite',
    'kalimpong': 'mountain',
    'kolkata': 'alluvial',
    'malda': 'alluvial',
    'murshidabad': 'alluvial',
    'nadia': 'alluvial',
    'north 24 parganas': 'alluvial',
    'paschim bardhaman': 'red_laterite',
    'paschim medinipur': 'red_laterite',
    'purba bardhaman': 'alluvial',
    'purba medinipur': 'coastal_sandy',
    'purulia': 'red_laterite',
    'south 24 parganas': 'coastal_sandy',
    'uttar dinajpur': 'alluvial',
}


# ──────────────────────────────────────────────
# STATE FALLBACK MAP (used if district not found)
# ──────────────────────────────────────────────
STATE_TO_SOIL_GROUP = {
    'punjab': 'alluvial', 'haryana': 'alluvial', 'uttar pradesh': 'alluvial',
    'bihar': 'alluvial', 'west bengal': 'alluvial', 'delhi': 'alluvial',
    'chandigarh': 'alluvial', 'assam': 'alluvial', 'lakshadweep': 'coastal_sandy',

    'maharashtra': 'black', 'gujarat': 'black', 'madhya pradesh': 'black',
    'dadra & nagar haveli': 'red_laterite', 'daman & diu': 'coastal_sandy',

    'karnataka': 'red_laterite', 'tamil nadu': 'red_laterite',
    'andhra pradesh': 'alluvial', 'telangana': 'black',
    'kerala': 'red_laterite', 'odisha': 'red_laterite',
    'chhattisgarh': 'red_laterite', 'jharkhand': 'red_laterite',
    'goa': 'red_laterite', 'pondicherry': 'alluvial',
    'andaman & nicobar': 'red_laterite',

    'himachal pradesh': 'mountain', 'jammu & kashmir': 'mountain',
    'uttarakhand': 'mountain', 'sikkim': 'mountain',
    'arunachal pradesh': 'mountain', 'nagaland': 'mountain',
    'manipur': 'mountain', 'mizoram': 'mountain',
    'meghalaya': 'mountain', 'tripura': 'mountain',
    'ladakh': 'mountain',

    'rajasthan': 'arid',
}


# ──────────────────────────────────────────────
# LOOKUP FUNCTION — use this in app.py
# ──────────────────────────────────────────────
def get_soil_group(city: str, state: str) -> str:
    """
    Returns soil group for a given city/district and state.
    Priority: district-level → state-level → default
    """
    city_key = city.strip().lower()
    state_key = state.strip().lower()

    # 1. Try exact district match
    if city_key in DISTRICT_SOIL_MAP:
        return DISTRICT_SOIL_MAP[city_key]

    # 2. Partial match (e.g. 'greater bangalore' → 'bangalore')
    for district, soil in DISTRICT_SOIL_MAP.items():
        if district in city_key or city_key in district:
            return soil

    # 3. Fall back to state-level
    return STATE_TO_SOIL_GROUP.get(state_key, 'default')


# ──────────────────────────────────────────────
# VERIFY COUNT
# ──────────────────────────────────────────────
if __name__ == '__main__':
    from collections import Counter
    print(f'Total district entries: {len(DISTRICT_SOIL_MAP)}')
    counts = Counter(DISTRICT_SOIL_MAP.values())
    print('Soil type distribution:')
    for soil, count in sorted(counts.items(), key=lambda x: -x[1]):
        print(f'  {soil:20s}: {count} districts')
